### ISSUE TITLE
Would it be possible to define link line colours for the Sankey network? 

### ISSUE THREAD

**Issue by najsaqib** [bcgov/WES_engagement_states#8]
I was looking at the documentation for the "networkD3" package and it appears that for a radialNetwork, there is an argument to define "linkColour," wherein one can presumably alter the default grey as the colour for the link lines.

Is there a way to do the same thing for a sankeyNetwork diagram? There doesn't appear to be a way to do it in the documentation, but perhaps there is a workaround? Would be interesting to see what the diagram in the app would look like if the link lines were the same colour as the node.

**Comment by daattali** [comment]
Welcome to github @najsaqib! :tada: 

You're right the documentation wasn't helpful, but it's fixed now.

However, the colours don't exactly match 100% with the bubble chart since the bubble chart has 6 different states of engagement while the sankey plot is 4 states + incomplete + N/A. But at least the same colour scheme is used now

**Comment by najsaqib** [comment]
Thanks for the welcome! Still getting used to Github and looking to take advantage of as many functionalities as I can grasp.

And thanks for the change. The node colours matching the bubble chart is definitely a very nice touch.

**Comment by daattali** [comment]
One awesome feature in github that you might have noticed is that in the message for my commit I made a reference to this issue, and that's why if you scroll up you'll actually see a link to my commit. So you can right away see the exact code that fixed this issue.

**Comment by najsaqib** [comment]
Yep, that does appear to be a very handy feature. A good incentive to remain active in the "issues" section too, I suppose.
